config/routes.rb
Rails.application.routes.draw do
  get 'welcome/Images'
  get 'welcome/index'
  get 'welcome/menu1'
  get 'articles/menu'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def index
	end
	def Images
		end
		def menu1
		end
		def menu
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def menu
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def Images
  end
  
  	  def index
	  end

	def menu1
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/menu.html.erb
<!DOCTYPE html>
<html lang="en">
<style type="text/css">
.header {
  background-color: royalblue;
  text-align: center;
  padding: 30px;
}
</style>
    
<div  class="header">
<ul class="nav">
    <li>
        <a href="#">Home</a>
    </li>

    <li>
        <a href="#">About</a>
        <ul>
            <li><a href="#">The product</a></li>

            <li><a href="#">Meet the team</a></li>
        </ul>
    </li>
    <li>
        <a href="#">Services</a>

        <ul>
            <li><a href="#">Sevice one</a></li>
            <li><a href="#">Sevice two</a></li>

            <li><a href="#">Sevice three</a></li>
            <li><a href="#">Sevice four</a></li>
        </ul>

    </li>
    <li>
        <a href="#">Product</a>
        <ul>
            <li><a href="#">Small product (one)</a></li>

            <li><a href="#">Small product (two)</a></li>
            <li><a href="#">Small product (three)</a></li>
            <li><a href="#">Small product (four)</a></li>

            <li><a href="#">Big product (five)</a></li>
            <li><a href="#">Big product (six)</a></li>
            <li><a href="#">Big product (seven)</a></li>

            <li><a href="#">Big product (eight)</a></li>
            <li><a href="#">Enormous product (nine)</a></li>
            <li><a href="#">Enormous product (ten)</a></li>

            <li><a href="#">Enormous product (eleven)</a></li>
        </ul>
    </li>
    <li>
        <a href="#">Contact</a>

        <ul>
            <li><a href="#">Out-of-hours</a></li>
            <li><a href="#">Directions</a></li>

        </ul>
    </li>
</ul>
</div>
</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DDRBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/Images.html.erb
	<!DOCTYPE html>
<html lang="en">
<style type="text/css">
	.background {
 /*background-image: url("/assets/kickstart-tech.jpg");*/
 background-color:yellow;
}
</style>
<h1 align="center" bgcolor="green"> Welcome Images
<a><img align="left" src="/assets/logo1.jpg" width="90" height="80"></a></h1>
<br>
<%=@a %> go to Welcome <%= link_to 'Index', welcome_index_path %> 
<br>

Image 
<img align="right" src="/assets/img1.jpg" width="100" height="80"/>
 
<body class="background">

	<img src="/assets/kickstart-tech.jpg"/>
	<img align="right" src="/assets/logo1.jpg" width="90" height="80">

	<a href="index.html" style="margin-left:10px;">MyHome </a>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<marquee direction="left" style= "color:blue"> Welcome </marquee>

<h1 align = "center" style= "color:green"> Ruby on Rails</h1>
<a href="https://guides.rubyonrails.org"> RailsGuide </a>

<h3 style="color:green;">This is a Workspace</h3>

<marquee style="color:red" direction="right" bgcolor="yellow">Hello Ruby</marquee>

<p> Hi Dev Welcom to Ruby World.</p>

<p color="red"> Hi RK , good mornig </p>

<p>	Good Day  	<a href="http://google.com" class="button"> Google</a></p>

<p>
	<font color="red"  > click on <a  href="welcome/menu1"><input type="submit" value="Go">
	</a></font>

<p><button onclick href="https://guides.rubyonrails.org/"> Rails Guide</button></p>

<hr><p style="color:yellow;"> Hydrabad</p>

<body 	style="background-color:powderblue;">Good Day</body>

<%=@a %> Find to welcome <%= link_to 'Index', welcome_index_path %> 

<%=@a %> Find to menu <%= link_to 'menu', articles_menu_path %> 
<br>
<%= link_to "Button Text", welcome_Images_path, class: 'btn btn-primary' %>
<br>
<%=@a %> Find to menu <%= link_to 'menu1', welcome_menu1_path %> 




</html>

app/views/welcome/menu1.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <h2>Dropdowns</h2>
  <p>The .dropdown class is used to indicate a dropdown menu.</p>
  <p>Use the .dropdown-menu class to actually build the dropdown menu.</p>
  <p>To open the dropdown menu, use a button or a link with a class of .dropdown-toggle and data-toggle="dropdown".</p>                                          
  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle"
            type="button" data-toggle="dropdown">Dropdown Example
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><a href="https://www.w3schools.com/html/html_examples.asp">HTML</a></li>
      <li><a href="https://www.w3schools.com/css/css_examples.asp">CSS</a></li>
      <li><a href="https://www.w3schools.com/js/">JavaScript</a></li>
    </ul>
  </div>
</div>

</body>
</html>